// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gorm.io/gorm"
	"henotech.net/infrastructure/datasource"
	"henotech.net/presentation/controller"
	"henotech.net/usecase"
)

// Injectors from wire.go:

func Init(db *gorm.DB) controller.TaskHandler {
	taskRepository := datasource.NewTaskRepository(db)
	taskUsecase := usecase.NewTaskUsecase(taskRepository)
	taskHandler := controller.NewTaskHandler(taskUsecase)
	return taskHandler
}
