version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    # command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - 15432:5432
    volumes:
      - go-dbdata:/var/lib/postgresql/data
      - ../db/conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ../db/init:/docker-entrypoint-initdb.d
  api:
    container_name: docker_go_api
    build:
      context: ./
      args:
        - GO_VERSION=${GO_VERSION}
        - API_CODE_WORKDIR=${API_CODE_WORKDIR}
    volumes:
      - ${API_CODE_LOCAL_PATH}:${API_CODE_WORKDIR}
    depends_on:
      - db
    ports:
      - ${API_PORT}:${API_PORT}
    tty: true

volumes:
  go-dbdata: